$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$installerPath = Join-Path $root 'scripts\Install-TradingLabPythonRuntime.ps1'
$setupPath = Join-Path $root 'scripts\setup.ps1'
$gatewayPath = Join-Path $root 'scripts\Test-GatewayRuntimeAcl.ps1'
$collectorPath = Join-Path $root 'scripts\Collect-RuntimeAclResults.ps1'
$gatewayEnvironmentPath = Join-Path $root 'scripts\Initialize-GatewayPythonEnvironment.ps1'
$gatewayStartPath = Join-Path $root 'scripts\start_gateway.ps1'

function Assert-True([bool] $Condition, [string] $Message) {
    if (-not $Condition) { throw $Message }
}

foreach ($path in @($installerPath, $setupPath, $gatewayPath, $collectorPath, $gatewayEnvironmentPath, $gatewayStartPath)) {
    $tokens = $null
    $errors = $null
    [void][System.Management.Automation.Language.Parser]::ParseFile(
        $path, [ref]$tokens, [ref]$errors
    )
    Assert-True ($errors.Count -eq 0) "PowerShell AST failed for ${path}: $($errors -join '; ')"
}

$installer = [System.IO.File]::ReadAllText($installerPath)
$setup = [System.IO.File]::ReadAllText($setupPath)
$gateway = [System.IO.File]::ReadAllText($gatewayPath)
$collector = [System.IO.File]::ReadAllText($collectorPath)
$gatewayEnvironment = [System.IO.File]::ReadAllText($gatewayEnvironmentPath)
$gatewayStart = [System.IO.File]::ReadAllText($gatewayStartPath)

foreach ($required in @(
    '#Requires -RunAsAdministrator',
    "`$pythonBase = 'C:\Program Files\AutomatonPython\3.14.5'",
    "`$expectedPythonVersion = '3.14.5'",
    "`$expectedInstallerLength = 30361968L",
    "`$expectedInstallerSha256 = 'f9c09f5ed6f796fd1a8bc5ddfa41715a494b453c4781f0e35d5077cf9fa58f6d'",
    "`$expectedLockSha256 = '68d14ddc9d943079e8f791bb8f276ae630f46c8ee8997b2bf2afeabed1e30d99'",
    'Get-AuthenticodeSignature',
    'O=Python Software Foundation',
    'Assert-OutsideUserProfiles',
    'Assert-NoReparseComponents',
    "Assert-ExactServiceIdentity 'AutomatonAgent' `$agentSid",
    "Assert-ExactServiceIdentity 'AutomatonGateway' `$gatewaySid",
    'Get-LocalUser -Name $Name',
    'Get-LocalGroupMember -SID $group.SID',
    "`$groups[0] -ne `$usersSid",
    'Assert-TreeNotModifiableByServices',
    'Protect-ExactRuntimeTree $pythonBase $true',
    'Assert-ExactBaseAcl $pythonBase',
    'InstallAllUsers=1',
    'Include_launcher=0',
    'PrependPath=0',
    'AppendPath=0',
    '--no-cache-dir --only-binary=:all: --require-hashes -r $lockPath',
    '& $basePython -I -m venv $stagingPath',
    'Assert-VenvPackages',
    'importlib.metadata.version("MetaTrader5")',
    'Move-Item -LiteralPath $venvPath -Destination $backupPath',
    'PYTHON_BASE_MACHINE_WIDE',
    'PYTHON_BASE_OUTSIDE_USER_PROFILE',
    'PYTHON_GATEWAY_EXECUTE_ACL',
    'PYTHON_GATEWAY_MODIFY_DENY_ACL',
    'VENV_BASE_OUTSIDE_USER_PROFILE',
    'GATEWAY_TEMP_OPERATIONAL_ONLY',
    '[System.IO.FileMode]::CreateNew',
    '$baseExists = Test-Path -LiteralPath $basePython -PathType Leaf',
    'if (-not $baseExists) {',
    '$venvCurrent = $false',
    'if (-not $venvCurrent) {',
    "trading_mode\s*:\s*OBSERVE_ONLY",
    "mt5_accessed = `$false",
    "automaton_started = `$false",
    "gateway_started = `$false"
)) {
    Assert-True ($installer.Contains($required)) "Python runtime gate lacks invariant: $required"
}

foreach ($forbidden in @(
    'Invoke-WebRequest', 'Start-BitsTransfer', 'curl.exe',
    'import MetaTrader5', '.initialize(', '.login(', '.symbol_select(',
    '.order_check(', '.order_send(', 'Start-Service', 'New-LocalUser',
    'Add-LocalGroupMember'
)) {
    Assert-True (-not $installer.Contains($forbidden)) "Python runtime gate contains forbidden action: $forbidden"
}

$dryRunIndex = $installer.IndexOf('if (-not $Apply) {')
Assert-True ($dryRunIndex -ge 0) 'Python runtime gate lacks explicit dry-run exit.'
foreach ($applyOnly in @(
    'Protect-ExactRuntimeTree $maintenanceRoot $false',
    'Start-Process -FilePath $InstallerPath',
    '& $basePython -I -m venv $stagingPath',
    'Move-Item -LiteralPath $venvPath -Destination $backupPath'
)) {
    Assert-True ($installer.LastIndexOf($applyOnly) -gt $dryRunIndex) "Mutation is not confined after dry-run exit: $applyOnly"
}
Assert-True `
    ($installer.IndexOf('$InstallerPath = Assert-Installer $InstallerPath') -lt $installer.IndexOf('Start-Process -FilePath $InstallerPath')) `
    'Verified installer must precede execution.'
Assert-True `
    (-not $installer.Contains("WriteAllText((Join-Path `$Root 'pyvenv.cfg')")) `
    'The venv redirector config must be generated by machine-wide Python, never edited manually.'
Assert-True `
    ($installer.Contains("`$agentSid") -and $installer.Contains('Protect-ExactRuntimeTree $pythonBase $true')) `
    'Agent SID must be considered for denial checks without being granted base runtime access.'
Assert-True `
    ($setup.Contains("`$machinePython = 'C:\Program Files\AutomatonPython\3.14.5\python.exe'")) `
    'Legacy setup must resolve only the managed machine-wide Python.'
Assert-True (-not $setup.Contains('& python -c')) 'Legacy setup must not resolve Python from PATH.'
Assert-True (-not $setup.Contains('python -m venv')) 'Legacy setup must not build a venv from an ambient interpreter.'
foreach ($required in @(
    "`$operationalRoot = [System.IO.Path]::GetFullPath(",
    "'C:\ProgramData\AutomatonMT5Lab\operational'",
    "`$env:TEMP = `$canonicalTemp",
    "`$env:TMP = `$canonicalTemp",
    "`$env:PYTHONDONTWRITEBYTECODE = '1'",
    '[System.IO.FileMode]::CreateNew',
    '[System.IO.FileAttributes]::ReparsePoint',
    'Gateway Python environment refuses an administrative token.'
)) {
    Assert-True ($gatewayEnvironment.Contains($required)) "Gateway private TEMP invariant is missing: $required"
}
Assert-True (-not $gatewayEnvironment.Contains('Windows\TEMP')) 'Gateway environment must not use Windows TEMP.'
Assert-True `
    ($gatewayStart.IndexOf('Initialize-GatewayPythonEnvironment') -lt $gatewayStart.IndexOf('& $python')) `
    'Gateway private TEMP must be set before the first Python process.'

foreach ($gate in @(
    'PYTHON_BASE_MACHINE_WIDE', 'PYTHON_BASE_OUTSIDE_USER_PROFILE',
    'PYTHON_GATEWAY_EXECUTE', 'PYTHON_GATEWAY_MODIFY_DENY',
    'VENV_BASE_OUTSIDE_USER_PROFILE'
)) {
    Assert-True ($gateway.Contains($gate)) "Gateway runtime report lacks gate: $gate"
    Assert-True ($collector.Contains($gate)) "Runtime collector lacks gate: $gate"
}

[pscustomobject]@{
    POWERSHELL_AST = 'PASS'
    PYTHON_INSTALLER_OFFLINE_VERIFIED = 'PASS'
    PYTHON_INSTALL_DRY_RUN_BOUNDARY = 'PASS'
    IDEMPOTENT_RESUME_DESIGN = 'PASS'
    PYTHON_BASE_MACHINE_WIDE = 'PASS'
    PYTHON_BASE_OUTSIDE_USER_PROFILE = 'PASS'
    PYTHON_GATEWAY_EXECUTE_GATE = 'PASS'
    PYTHON_GATEWAY_MODIFY_DENY_GATE = 'PASS'
    VENV_REBUILT_FROM_MACHINE_BASE = 'PASS'
    VENV_HASH_LOCK_ONLY = 'PASS'
    VENV_BASE_OUTSIDE_USER_PROFILE = 'PASS'
    SERVICE_RUNTIME_USER_PROFILE_DEPENDENCY_DENY = 'PASS'
    GATEWAY_TEMP_OPERATIONAL_ONLY = 'PASS'
    MT5_NOT_ACCESSED = 'PASS'
} | ConvertTo-Json
